app:

server:
  port: ${CORE_CONTRACTOR_PORT}
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=contractor&reWriteBatchedInserts=true
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      jdbc:
        time_zone: UTC
    show-sql: true
    properties:
      hibernate.default_schema: contractor
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.jdbc.batch_size: 100

  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: contractor
    table: flyway_contractor_history
    
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /api/contractor/v3/api-docs
  swagger-ui:
    enabled: true
    csrf:
      enabled: true
    path: /api/contractor/swagger-ui.html


logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.web.cors: ${LOG_LEVEL_SPRING_WEB_CORS:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:DEBUG}
    com.ginkgooai: ${LOG_LEVEL_GINKGOOAI:DEBUG}
